# Generated by Django 6.0.5 on 2026-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tendering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
