# Generated by Django 6.0.5 on 2026-05-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tendering", "0003_bid_company_name_bid_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="bid",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="tender",
        ),
        migrations.AddField(
            model_name="notification",
            name="bid_title",
            field=models.CharField(default="title", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="tender_title",
            field=models.CharField(default="title", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="Tendering.company",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to="Tendering.company",
            ),
        ),
    ]
