# Generated by Django 6.0.6 on 2026-06-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tendering', '0007_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_bid', 'New Bid'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('tender_approved', 'Tender Approved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tender',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TenderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('PayPal', 'PayPal')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tendering.tender')),
            ],
        ),
    ]
