# Generated by Django 5.2.13 on 2026-07-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tendering', '0008_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Tendering.tender'),
        ),
        migrations.AlterField(
            model_name='tenderpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Sham Cash', 'Sham Cash'), ('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('PayPal', 'PayPal')], max_length=50),
        ),
    ]
