# Generated by Django 5.2.13 on 2026-08-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tendering', '0009_notification_tender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
